### ISSUE TITLE
Nothing works on Linux

### ISSUE THREAD

**Issue by spetafree** [lorenzo2897/vscode-ipe#159]
Hi.
First of all - great work. I was looking for something just like this. 

I tried to install the extension on vscode (latest version - 1.25) on linux (brand new Ubuntu 16.04 installation) from the marketplace (version 1.0.1).

It installs, but no command works. I get 'missing command' error for any IPE command I try.

Are there any more details that I can provide to help reproduce this?

**Comment by lorenzo2897** [comment]
Hi @spetafree, thanks for trying out our extension!
Make sure you have a Python or R file open in the active editor, and that you run the "Open output pane" before any other command. Does that fix the issue?

**Comment by xingru-xu** [comment]
I have the same issue. 
I installed the extension on VSCode 1.25 on macOS 10.13.4.
I get "command 'ipe.XXX' not found" for all IPE command. 
I think this project is excellent, but it doesn't work for me. That's very frustrating.

**Comment by louiskueh** [comment]
Hi @spetafree @icy-xu,

We believe we've found the issue and should be coming up with a fix shortly - will keep you guys updated

**Comment by spetafree** [comment]
> Make sure you have a Python or R file open in the active editor, and that you run the "Open output pane" before any other command. Does that fix the issue?

That is exactly the flow I have used, when I encountered the issue. (Python file)

**Comment by LukeyQ1** [comment]
Hi @spetafree @icy-xu 
It was a slight oversight on my part when repackaging the latest release but I believe it is now fixed in the 1.0.2 (#160) release on the Marketplace.

Thanks for trying our extension and I hope it runs correctly now :)

**Comment by spetafree** [comment]
Hi @LukeyQ1, 
Thanks for your work but the issue is not solved.

I still see ipe.showWebview not found error
also after reinstall, when trying to open the output pane.

In the console I see also "ipe.stuff appears multiple times in the commands section",
And "cannot find module ./CardManager"

Thanks for your work

**Comment by LukeyQ1** [comment]
@spetafree the problem only occurs when run on linux and I just found out the source of this issue is an uppercase letter where it should be lower case 🤦‍♂️ .
I'm just going over things before I push the update to the marketplace, if you would like to use it before then you can install from VSIX using the file link below. If you have any more issues with this please let me know.

[neuron-IPE-1.0.3 Preview](https://github.com/lorenzo2897/vscode-ipe/files/2210829/neuron-IPE-1.0.3.vsix.zip)

Edit: Now available on Marketplace

**Comment by spetafree** [comment]
Nice catch. This is *very* common when developing cross platform on Windows from my experience... 
Thanks a lot, I'll try it out.
