### ISSUE TITLE
"Could not start a notebook automatically"

### ISSUE THREAD

**Issue by veonua** [lorenzo2897/vscode-ipe#180]
Please give at least some hints what happened, there is nothing in console

**Comment by veonua** [comment]
/**
     * Pattern which matches Jupyter Notebook urls.
     */
    private static urlPattern = /http:\/\/localhost:[0-9]+\/\?token=[a-z0-9]+/g;


ok, that's invalid assumption, as my jupyter ouput is 

[I 23:32:10.240 NotebookApp] The port 8888 is already in use, trying another port.
[I 23:32:10.241 NotebookApp] The port 8889 is already in use, trying another port.
[I 23:32:10.241 NotebookApp] The port 8890 is already in use, trying another port.
[I 23:32:10.241 NotebookApp] The port 8891 is already in use, trying another port.
[I 23:32:10.241 NotebookApp] The port 8892 is already in use, trying another port.
[I 23:32:10.287 NotebookApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 23:32:10.287 NotebookApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 23:32:10.288 NotebookApp] Serving notebooks from local directory: /home/veon/work
[I 23:32:10.288 NotebookApp] The Jupyter Notebook is running at:
[I 23:32:10.288 NotebookApp] http://(veon-XPS-15-9550 or 127.0.0.1):8869/


so neuron run jupyter several times but unable to extract url

**Comment by pavanagrawal123** [comment]
I fixed this issue in a fork here: https://github.com/pavanagrawal123/VSNotebooks it's currently in the beta version of the extension so try it out and let me know if it works for you!

**Comment by veonua** [comment]
@pavanagrawal123 unfortunately have no idea how to add plugins from github, Will appreciate if you could provide any instructions

**Comment by iamaziz** [comment]
I have the same problem. @pavanagrawal123 I installed the beta fork, it did not solve the problem in my case. However, I suspect the issue might be related to Jupyter's installation.

**Comment by MikeYuanMY** [comment]
I tried the beta version of the fork one. Unfortunately, still cannot run it. I can see the extension trying to start jupiter kernel at location /anaconda/bin on my machine

**Comment by mirkancal** [comment]
I have Jupyter installed in my conda environment. I get the same error.

**Comment by pavanagrawal123** [comment]
@iamaziz @Mikeymice @mirkancal could y'all file an issue in the fork repo with some logs, etc?

**Comment by mirkancal** [comment]
@pavanagrawal123 I can use jupyter notebooks in vscode without a problem, so I didn't installed your fork. But I can't use it with neuron extension, it gives the error.

**Comment by lorenzo2897** [comment]
You should be able to connect to a Jupyter instance manually by using the `Open Output Pane with Existing Jupyter Notebook` command.
